### ISSUE TITLE
Unable to connect to NATS server via Android Studio

### ISSUE THREAD

**Issue by dalew75** [nats-io/nats.java#402] opened 2021-01-31 17:02 UTC
I'm using the following line (Kotlin) to connect to the demo NATS server in Android / Android Studio:
`val nc: Connection = Nats.connect("nats://demo.nats.io:4222");`

But it throws an IOException without any other information
`java.io.IOException: Unable to connect to NATS server.
`
Same thing if I try to specify Options/timeout:
`val options = Options.Builder().server("nats://demo.nats.io:4222").connectionTimeout(Duration.ofSeconds(10)).build()`

Do you know why this might be?  Permissions on a port?

I did add these permissions to the manifest and that was no help:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```
https://developer.android.com/training/basics/network-ops/connecting

It works fine in my regular Java/Groovy(Grails) webapp:
`Connection nc =  Nats.connect('nats://demo.nats.io:4222');`

And also in node.js:
`const nc = NATS.connect(`nats://demo.nats.io:4222`);`

I also tried this using the ip of the NATS server I set up and same thing (fails on Android Studio, but fine in java/node apps)

I installed nats via Gradle:
`implementation 'io.nats:jnats:2.8.0''`

**Comment by scottf** [comment] 2021-02-02 12:52
I wrote a plain vanilla publish / subscribe to the demo servers against the 2.8.0 current release. 

See https://github.com/nats-io/kotlin-nats-examples

So my guess is that it's something to do with an Android networking library.

**Comment by dalew75** [comment] 2021-02-03 14:37
Thanks @scottf ... That's my thought too, but there's no more information on it.  I originally was using this Android specific fork of nats-java, but that had the same issue.  https://github.com/SpotOnInc/nats-android

When investigating, I went on to use the standard nats-java lib, but no improvement

**Comment by iivanf** [comment] 2021-03-09 14:35
I had the same error, you just need to make the connection in a different thread.

```kotlin
  Thread {
            val options: Options = Options.Builder().server("nats://demo.nats.io:4222").build()
            try {
                val nc : Connection = Nats.connect(options)
                print("Done")
            } catch (exp: Exception) {
                print(exp.printStackTrace())
            }
        }.start()
```

**Comment by scottf** [comment] 2021-03-09 19:34
@dalew75 @iivanf So I think the problem is in fact doing the connection in a different thread. Currently the first connect requires a blocking call. We have an issue request to change this, https://github.com/nats-io/nats.java/issues/406 and are considering options.

**Comment by dalew75** [comment] 2021-03-30 16:29
Thanks @iivanf !!  Do you happen to have a working basic Android studio project where this works and connects to the demo NATS server?  I still cannot get it to work!

**Comment by iivanf** [comment] 2021-04-09 17:23
Yes @dalew75 u can check it here https://github.com/iivanf/NatsKotlin

**Comment by dalew75** [comment] 2021-04-09 18:35
Awesome @iivanf .. thank you so much, works like a charm 💯

**Comment by scottf** [comment] 2021-04-30 10:48
Closing, many thanks to @iivanf for his contribution.

**Closed** 2021-04-30 10:49 UTC
Labels: 🎏cannot reproduce

**Comment by sayalipathak7** [comment] 2024-07-10 17:15
@iivanf 
I tried using the NatsKotlin project from [NatsKotlin](https://github.com/iivanf/NatsKotlin) that you provided. It's working for me on the server nats://demo.nats.io:4222. However, on my local machine where I have a NATS server running at nats://localhost:4222, it is not working. What could be the reason? Could you please help me with this issue?
