### ISSUE TITLE
Failure creating a subscription on a (fairly) new connection

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nats.java#316] opened 2020-05-28 17:21 UTC
I'm encountering an exception when creating a subscription on a new connection.  The new connection has only had a few messages passed through it based on the message stats.  I'm working on isolating a use case and will add to this issue if successful.

The goal here is to have an application receive a message, and from within the callback create a new connection and subscribe.  The connection used here and the attempt to subscribe were created/called from within the callback of a different connection.

```java
            System.out.println("setupMessageHandling, conn="+ c);
            d = c.createDispatcher(this);
            d.subscribe("control.*");
            c.flush(Duration.ofSeconds(2));
```

What's odd is that that if the connection has never been used to publish a message this does not occur.

The result:

```text
NATS @ ~/Dropbox/go/src/github.com/ColinSullivan1/java-examples () $ ./publoss.sh 
setupMessageHandling, conn=io.nats.client.impl.NatsConnection@31221be2
Sending 100000 messages of 128 bytes on foo, server is nats://localhost:4222
Received control message on control.migrate.
newConn=io.nats.client.impl.NatsConnection@4e3e8e61
oldConn=io.nats.client.impl.NatsConnection@31221be2
publishing paused...
publishing paused...
NATS Connection Event: nats: connection closed
Done with migration.
Conn Statistics: 
### Connection ###
Reconnects:                      0
### Reader ###
Messages in:                     0
Bytes in:                        0
### Writer ###
Messages out:                    9
Bytes out:                       1,152
setupMessageHandling, conn=io.nats.client.impl.NatsConnection@4e3e8e61
Migration exception: Output queue is full 0
java.lang.IllegalStateException: Output queue is full 0
	at io.nats.client.impl.MessageQueue.push(MessageQueue.java:122)
	at io.nats.client.impl.MessageQueue.push(MessageQueue.java:108)
	at io.nats.client.impl.NatsConnectionWriter.queue(NatsConnectionWriter.java:191)
	at io.nats.client.impl.NatsConnection.queueOutgoing(NatsConnection.java:1316)
	at io.nats.client.impl.NatsConnection.sendSubscriptionMessage(NatsConnection.java:938)
	at io.nats.client.impl.NatsConnection.createSubscription(NatsConnection.java:908)
	at io.nats.client.impl.NatsDispatcher.subscribeImpl(NatsDispatcher.java:252)
	at io.nats.client.impl.NatsDispatcher.subscribe(NatsDispatcher.java:194)
	at io.nats.java.examples.ControlPlane.setupMessageHandling(ControlPlane.java:32)
	at io.nats.java.examples.ControlPlane.migrate(ControlPlane.java:63)
	at io.nats.java.examples.ControlPlane.onMessage(ControlPlane.java:77)
	at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The problem appears to be in adding to an empty LinkedBlockingQueue.

https://github.com/nats-io/nats.java/blob/507490d9941a4dc5fe8333ad1931bd14818a66d2/src/main/java/io/nats/client/impl/MessageQueue.java#L121-L123

## Environment
MacOS Catalina

 $ java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

Any ideas?  Thanks!

**Comment by ColinSullivan1** [comment] 2020-05-28 19:15
Here's test code that will reproduce this issue.  Maybe I'm doing something wrong...  If I comment out the close in the callback, it works.  That being said, I don't see how close on one connection should affect another.

## Code 
```java
    static public void main(String argv[]) {
        try {
            // setup connection
            Connection nc = Nats.connect("localhost:4222");

            // setup a message handler that creates another connection
            // and closes the original connection.
            MessageHandler mh = new MessageHandler() {
                public void onMessage(Message msg) throws InterruptedException {
                    try {
                        // create a new connection here
                        Connection nc2 = Nats.connect("localhost:4222");
            
                        // close the original conn
                        try {
                          nc.close();
                        } catch (Exception e) {
                            // Doesn't get hit
                            e.printStackTrace();
                        }
            
                        // recreate subscription on the new connection
                        Dispatcher d2 = nc2.createDispatcher(this);
                        d2.subscribe("foo");  // <- exception here
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } 
            };

            // setup handler and subscription
            Dispatcher d1 = nc.createDispatcher(mh);
            d1 .subscribe("foo");
            nc.flush(Duration.ofSeconds(2));

            // Invoke the callback from a completely different connection
            Nats.connect("localhost:4222").publish("foo", new byte[64]);

            Thread.sleep(2000);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("Done");
    }
```

## Output

```text
bash-3.2$  /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -cp /var/folders/2x/d1g9l2xd5xl17ktltf8pl7wh0000gn/T/cp_emg817tpcc6tlwijoobi02k26.jar io.nats.java.examples.Example 
java.lang.IllegalStateException: Output queue is full 0
        at io.nats.client.impl.MessageQueue.push(MessageQueue.java:122)
        at io.nats.client.impl.MessageQueue.push(MessageQueue.java:108)
        at io.nats.client.impl.NatsConnectionWriter.queue(NatsConnectionWriter.java:191)
        at io.nats.client.impl.NatsConnection.queueOutgoing(NatsConnection.java:1316)
        at io.nats.client.impl.NatsConnection.sendSubscriptionMessage(NatsConnection.java:938)
        at io.nats.client.impl.NatsConnection.createSubscription(NatsConnection.java:908)
        at io.nats.client.impl.NatsDispatcher.subscribeImpl(NatsDispatcher.java:252)
        at io.nats.client.impl.NatsDispatcher.subscribe(NatsDispatcher.java:194)
        at io.nats.java.examples.Example$1.onMessage(Example.java:32)
        at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Done
```

**Comment by sasbury** [comment] 2020-05-28 20:58
If this is only the latest version it could be related to the pr that put a max size on the queue.On May 28, 2020 12:15 PM, Colin Sullivan <notifications@github.com> wrote:
Here's test code that will reproduce this issue.  Maybe I'm doing something wrong...  If I comment out the close in the callback, it works.  That being said, I don't see how close on one connection should affect another.
Code
    static public void main(String argv[]) {
        try {
            // setup connection
            Connection nc = Nats.connect("localhost:4222");

            // setup a message handler that creates another connection
            // and closes the original connection.
            MessageHandler mh = new MessageHandler() {
                public void onMessage(Message msg) throws InterruptedException {
                    try {
                        // create a new connection here
                        Connection nc2 = Nats.connect("localhost:4222");
            
                        // close the original conn
                        try {
                          nc.close();
                        } catch (Exception e) {
                            // Doesn't get hit
                            e.printStackTrace();
                        }
            
                        // recreate subscription on the new connection
                        Dispatcher d2 = nc2.createDispatcher(this);
                        d2.subscribe("foo");  // <- exception here
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                } 
            };

            // setup handler and subscription
            Dispatcher d1 = nc.createDispatcher(mh);
            d1 .subscribe("foo");
            nc.flush(Duration.ofSeconds(2));

            // Invoke the callback from a completely different connection
            Nats.connect("localhost:4222").publish("foo", new byte[64]);

            Thread.sleep(2000);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("Done");
    }
Output
bash-3.2$  /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -cp /var/folders/2x/d1g9l2xd5xl17ktltf8pl7wh0000gn/T/cp_emg817tpcc6tlwijoobi02k26.jar io.nats.java.examples.Example 
java.lang.IllegalStateException: Output queue is full 0
        at io.nats.client.impl.MessageQueue.push(MessageQueue.java:122)
        at io.nats.client.impl.MessageQueue.push(MessageQueue.java:108)
        at io.nats.client.impl.NatsConnectionWriter.queue(NatsConnectionWriter.java:191)
        at io.nats.client.impl.NatsConnection.queueOutgoing(NatsConnection.java:1316)
        at io.nats.client.impl.NatsConnection.sendSubscriptionMessage(NatsConnection.java:938)
        at io.nats.client.impl.NatsConnection.createSubscription(NatsConnection.java:908)
        at io.nats.client.impl.NatsDispatcher.subscribeImpl(NatsDispatcher.java:252)
        at io.nats.client.impl.NatsDispatcher.subscribe(NatsDispatcher.java:194)
        at io.nats.java.examples.Example$1.onMessage(Example.java:32)
        at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:98)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Done

**Comment by sasbury** [comment] 2020-05-29 17:02
looks like you an Richard worked on that one, maybe he has some ideas, i will try to look if you don't see anything

**Comment by ColinSullivan1** [comment] 2020-06-08 22:38
I think I've found out the issue, or at least have a working theory.  The initial connection's close from within the callback will interrupt the callback thread itself, so the first "interruptable" API after the close throws an InterruptedException.  In the example provided it is `queue.offer` found in subscribe:

https://github.com/nats-io/nats.java/blob/507490d9941a4dc5fe8333ad1931bd14818a66d2/src/main/java/io/nats/client/impl/MessageQueue.java#L144-L151

`offer` was throwing an interrupted exception, so the method returned false. Calling code assumed the queue was full upon a false return code.

In the example code if called `Thread.sleep(1)` immediately after the close, the sleep is interrupted instead.

To resolve, if a connection is closed, should user code in the callback be interrupted, or should the callback be allowed to finish?

@RichardHightower, @sasbury , wdyt?

**Comment by sasbury** [comment] 2020-06-09 04:15
Hm, is the thread interrupted? If so, I don’t recall ever writing that, interrupting threads is generally bad. I would say that the callback should complete.

**Comment by RichardHightower** [comment] 2020-06-09 14:04
I will reproduce it locally today and try to reason on it a bit.

**Comment by ivanr** [comment] 2020-08-17 14:15
Related: https://github.com/nats-io/nats.java/issues/305

**Comment by mdford** [comment] 2020-11-19 23:21
Was there ever a "fix" for this?  I have inherited a project that I am attempting to retrofit with Nats.  I am encountering the same bug/message due to the way the original code was written.  There are times when the current code will "timeout" in a function and does a retry which calls the section of code again with the .publish() call which then throws the `java.lang.IllegalStateException: Output queue is full 0` exception.  Once this happens, the publish() method will throw this every time it is called.  How did you resolve this or did you find a workaround that will allow publish to be called again from an interrupted thread?  

Thanks!

**Comment by scottf** [comment] 2021-03-13 15:12
> The initial connection's close from within the callback will interrupt the callback thread itself, so the first "interruptable" API after the close throws an InterruptedException. 

Yes, I came to the same conclusion. Connection 1 subscribes to a message and then receives that message. While processing the receive, the code tries to close the connection that it is currently on, which makes sure that there are no messages in flight. But there are, so it can't close, so it times out, throws an interrupted exception, which basically leaves the connection in a broken state.
Then when you open a new connection and try to publish, even though it's a new connection, it's the same vm, and the underlying queue mechanism shares a lock because it's the **same thread**, which can't be acquired so the queue operation fails. The error message queue is full is misleading because the queue is not full, but the queue does not discern between the queue being full failure and other failures while offering something to the queue.

This is why closing after the subscribe works and closing before the subscribe fails. So here is a fix. Make the second subscribe in a different thread.

```
nc2.getOptions().getExecutor().submit(() -> {
    Dispatcher d2 = nc2.createDispatcher(this);
    d2.subscribe("foo");  // <- exception here
});
```

**Comment by scottf** [comment] 2022-02-23 14:05
Closing, not response. Fixed with code example in comments

**Closed by scottf** 2022-02-23 14:05 UTC
Labels: 🛠 fixed waiting confirmation
