### ISSUE TITLE
No connection possible when using multiple servers

### ISSUE THREAD

**Issue by wutkemtt** [nats-io/nats.java#340] opened 2020-09-01 12:47 UTC
We are having problems to connect to our NATS servers when using multiple server URLs in the connection options. On client side we get this error:
`Caused by: java.io.IOException: SSL required by server.
INFO   | jvm 1    | 2020/08/26 14:55:58 | 	at io.nats.client.impl.NatsConnection.upgradeToSecureIfNeeded(NatsConnection.java:537) ~[jnats-2.6.6.jar!/:2.6.6]
INFO   | jvm 1    | 2020/08/26 14:55:58 | 	at io.nats.client.impl.NatsConnection$1.call(NatsConnection.java:427) ~[jnats-2.6.6.jar!/:2.6.6]

INFO   | jvm 1    | 2020/08/26 14:55:58 | Caused by: java.io.IOException: Unable to connect to NATS servers: tls://nats-1.mycompany.com:4222, tls://nats-2.mycompany.com:4222.
INFO   | jvm 1    | 2020/08/26 14:55:58 | 	at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:236) ~[jnats-2.6.6.jar!/:2.6.6]
INFO   | jvm 1    | 2020/08/26 14:55:58 | 	at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29) ~[jnats-2.6.6.jar!/:2.6.6]
INFO   | jvm 1    | 2020/08/26 14:55:58 | 	at io.nats.client.Nats.createConnection(Nats.java:247) ~[jnats-2.6.6.jar!/:2.6.6]
INFO   | jvm 1    | 2020/08/26 14:55:58 | 	at io.nats.client.Nats.connect(Nats.java:164) ~[jnats-2.6.6.jar!/:2.6.6]`

On server side we see this error:
`[2212] 2020/09/01 14:28:11.337259 [ERR] 10.254.65.170:64088 - cid:2044 - TLS handshake error: EOF
[2212] 2020/09/01 14:28:57.334387 [ERR] 10.254.65.170:64496 - cid:2046 - TLS handshake error: EOF
[2212] 2020/09/01 14:33:38.183469 [ERR] 10.254.65.170:50443 - cid:2052 - TLS handshake error: EOF
[2212] 2020/09/01 14:33:54.777795 [ERR] 10.254.65.170:50535 - cid:2053 - TLS handshake error: EOF`

The same configuration and connection works, when we use a single server Url only. It seems the ssl context is not used properly when creating a connection or reconnecting to multiple servers.

Maybe this issue is related to #279

**Comment by scottf** [comment] 2021-03-14 14:22
@wutkemtt Can you check against the 2.9.0-SNAPSHOT? Issue https://github.com/nats-io/nats.java/issues/279 suggests that this has been fixed.

**Comment by danpoland** [comment] 2021-04-27 16:41
I can confirm this is still an issue on  release `2.10.0`.

**Comment by danpoland** [comment] 2021-04-28 13:40
I am on release `2.10.0` and running two NATS JetStream servers locally.

This code does not work:
```
Options options = new Options.Builder()
            .server("opentls://localhost:4222")
            .server("opentls://localhost:4223")
            .build();

conn = Nats.connect(options);
```

It causes this Java error:
```
Caused by: java.io.IOException: Unable to connect to NATS servers: opentls://localhost:4223, opentls://localhost:4222
        at io.nats.client.impl.NatsConnection.connect(NatsConnection.java:202) ~[jnats-2.10.0.jar:2.10.0]
        at io.nats.client.impl.NatsImpl.createConnection(NatsImpl.java:29) ~[jnats-2.10.0.jar:2.10.0]
        at io.nats.client.Nats.createConnection(Nats.java:271) ~[jnats-2.10.0.jar:2.10.0]
        at io.nats.client.Nats.connect(Nats.java:186) ~[jnats-2.10.0.jar:2.10.0]
```

In the NATS logs I see:
```
nats2_1     | [1] 2021/04/28 13:25:37.066030 [ERR] 172.19.0.1:61118 - cid:16 - TLS handshake error: EOF
nats1_1     | [1] 2021/04/28 13:25:37.068779 [ERR] 172.19.0.1:60396 - cid:17 - TLS handshake error: EOF
```

Passing the comma seperated string directly to the `connect` method fails with the above errors as well.
```
conn = Nats.connect("opentls://localhost:4222,opentls://localhost:4223");
```

Passing a single URI in both examples above works fine:
```
Options options = new Options.Builder()
            .server("opentls://localhost:4222")
            .build();

conn = Nats.connect(options);
```

```
conn = Nats.connect("opentls://localhost:4223");
```

Maybe the `opentls` protocol has something to do with it?

**Comment by scottf** [comment] 2021-04-28 14:36
@danpoland I'm looking into `opentls://` based on your last comment. Based on everything else in this issue and the comments in #279 I was only checking on `tls://` I'll get back to you

**Comment by scottf** [comment] 2021-04-28 15:55
@danpoland I found the issue and will have a fix released in 2.11.0 by end of week.
It was our options code was only considering if there was exactly 1 server AND the sslContext had not been set, we would set the context ourselves. But since there were more than 1 server we never set the sslContext, so the connection cold not upgrade

**Comment by scottf** [comment] 2021-04-29 10:27
This is fixed in PR https://github.com/nats-io/nats.java/pull/455

**Comment by scottf** [comment] 2021-04-30 10:00
Fixed in https://github.com/nats-io/nats.java/pull/455.

**Closed by scottf** 2021-04-30 10:00 UTC
Labels: 🛠 fixed waiting confirmation
